/* Generates supabase/seed.sql from the catalog in src/data/mock.ts — the same
   deterministic generators the M0 prototype used, so every name, minute count,
   and lesson tree matches data.js bit-for-bit.

   Run:  npx tsx scripts/generate-seed.ts
   The output file is committed; regenerate whenever the catalog or the
   javascript-basics articles change. */

import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { CATEGORIES, topicsFor, lessonsFor } from '../src/data/mock'

const here = dirname(fileURLToPath(import.meta.url))
const OUT = join(here, '..', 'supabase', 'seed.sql')

/* A few non-published topics so the admin status filters are demonstrable
   (same slugs the M0 mock flags). */
const STATUS_OVERRIDES: Record<string, 'draft' | 'review'> = {
  'ml-foundations-foundations': 'draft',
  'public-speaking-foundations': 'review',
  'ui-design-foundations': 'draft',
}

/* Real articles for the hero topic, matched to lessons by position. */
const JS_BASICS_BODIES = readdirSync(join(here, 'content', 'javascript-basics'))
  .filter((f) => f.endsWith('.md'))
  .sort()
  .map((f) => readFileSync(join(here, 'content', 'javascript-basics', f), 'utf8').trim())

function esc(s: string): string {
  return s.replace(/'/g, "''")
}

function genericBody(title: string, topicName: string): string {
  return `Every lesson on Primer follows the same rhythm: a short explanation, a worked example, and an exercise to prove it stuck.

## The idea

**${title}** is one step in *${topicName}*. Work through it in order — each lesson builds on the one before it.

## Try it yourself

- Apply the idea to a small example of your own.
- Explain it out loud in one sentence; if you can't, reread the section above.
- Note one question to bring to the next lesson.

## What to remember

1. Small steps, in order, beat big leaps.
2. Practice is the point — reading alone doesn't stick.
3. Mark the lesson complete when you can do it, not just follow it.`
}

const lines: string[] = []
lines.push('-- GENERATED by scripts/generate-seed.ts — do not edit by hand.')
lines.push('-- Full Primer catalog: 8 categories, 31 subcategories, 120 topics with units + lessons.')
lines.push('')
lines.push('begin;')
lines.push('')
lines.push('-- Fail closed: never wipe a database that has learner data in it.')
lines.push(`do $guard$
begin
  if exists (select 1 from public.lesson_progress)
     or exists (select 1 from public.profiles where role = 'learner') then
    raise exception 'refusing to reseed: learner data present';
  end if;
end
$guard$;`)
lines.push('')
lines.push('truncate public.categories, public.subcategories, public.topics, public.units, public.lessons restart identity cascade;')
lines.push('')

let subId = 0
let topicId = 0
let unitId = 0
let lessonId = 0

const catRows: string[] = []
const subRows: string[] = []
const topicRows: string[] = []
const unitRows: string[] = []
const lessonRows: string[] = []

CATEGORIES.forEach((cat, ci) => {
  const catId = ci + 1
  catRows.push(
    `(${catId}, '${esc(cat.slug)}', '${esc(cat.name)}', '${esc(cat.desc)}', '${esc(cat.icon)}', '${cat.tint}', '${cat.tintInk}', ${ci + 1})`,
  )
  cat.subs.forEach((sub, si) => {
    subId++
    const thisSubId = subId
    subRows.push(`(${thisSubId}, ${catId}, '${esc(sub.slug)}', '${esc(sub.name)}', '${esc(sub.desc)}', ${si + 1})`)

    topicsFor(sub.slug).forEach((topic, ti) => {
      topicId++
      const thisTopicId = topicId
      const status = STATUS_OVERRIDES[topic.slug] ?? 'published'
      topicRows.push(
        `(${thisTopicId}, ${thisSubId}, '${esc(topic.slug)}', '${esc(topic.name)}', '${esc(topic.desc)}', '${topic.level}', '${status}', ${ti + 1})`,
      )

      let n = 0
      lessonsFor(topic).forEach((unit, ui) => {
        unitId++
        const thisUnitId = unitId
        unitRows.push(`(${thisUnitId}, ${thisTopicId}, '${esc(unit.unit)}', ${ui + 1})`)
        unit.items.forEach((item) => {
          lessonId++
          n++
          const body =
            topic.slug === 'javascript-basics'
              ? JS_BASICS_BODIES[n - 1] ?? genericBody(item.title, topic.name)
              : genericBody(item.title, topic.name)
          lessonRows.push(
            `(${lessonId}, ${thisTopicId}, ${thisUnitId}, '${esc(item.title)}', '${esc(body)}', ${item.mins}, ${n})`,
          )
        })
      })
    })
  })
})

lines.push('insert into public.categories (id, slug, name, description, icon, tint, tint_ink, sort_order) overriding system value values')
lines.push(catRows.join(',\n') + ';')
lines.push('')
lines.push('insert into public.subcategories (id, category_id, slug, name, description, sort_order) overriding system value values')
lines.push(subRows.join(',\n') + ';')
lines.push('')
lines.push('insert into public.topics (id, subcategory_id, slug, title, description, level, status, sort_order) overriding system value values')
lines.push(topicRows.join(',\n') + ';')
lines.push('')
lines.push('insert into public.units (id, topic_id, title, sort_order) overriding system value values')
lines.push(unitRows.join(',\n') + ';')
lines.push('')
lines.push('insert into public.lessons (id, topic_id, unit_id, title, body_md, minutes, sort_order) overriding system value values')
lines.push(lessonRows.join(',\n') + ';')
lines.push('')
lines.push('-- Resync identity sequences: explicit-id inserts do not advance them, and')
lines.push("-- without this the first admin insert would fail with a duplicate-PK error.")
for (const t of ['categories', 'subcategories', 'topics', 'units', 'lessons']) {
  lines.push(`select setval(pg_get_serial_sequence('public.${t}', 'id'), (select max(id) from public.${t}));`)
}
lines.push('')
lines.push('commit;')
lines.push('')

writeFileSync(OUT, lines.join('\n'), 'utf8')

console.log(
  `seed.sql written: ${CATEGORIES.length} categories, ${subId} subcategories, ${topicId} topics, ${unitId} units, ${lessonId} lessons`,
)
if (JS_BASICS_BODIES.length !== 13) {
  console.warn(`WARNING: expected 13 javascript-basics articles, found ${JS_BASICS_BODIES.length}`)
}
